src/minerfund.cpp, src/rpc/mining.cpp, src/test/miner_tests.cpp, test/functional/abc_feature_minerfund.py, test/functional/abc_mining_basic.py
- Enforce whitelist from genesis in `GetMinerFundWhitelist`.
- Set `minerFundMinValue` to miner fund value from genesis in `getblocktemplate`.
- Update `CreateNewBlock_validity`; keep additional coinbase outputs generated by `getblocktemplate` and add `MINERREWARD` calculated from `GetMinerFundAmount`.
- Remove activation logic from `test/functional/abc_feature_minerfund.py`
- Remove activation logic from `test/functional/abc_mining_basic.py`, and verify from genesis.
NOTE: in `test/functional/abc_mining_basic.py`, `getblocktemplate` always fails if called from genesis, where it reports: `JSONRPC error: Bitcoin ABC is in initial sync and waiting for blocks...`.
This needs to be fixed before mining operations can start.
=> Coinbase rule from genesis

src/miner.cpp, src/test/miner_tests.cpp, src/validation.cpp
- Remove logic causing CTOR to activate and always keep it as active.
- Fix `CreateNewBlock_validity`, which relied on TTOR.
=> Ctor from genesis

src/consensus/consensus.h, src/consensus/tx_verify.cpp, src/policy/policy.h, src/test/miner_tests.cpp, src/validation.cpp, test/functional/feature_bip68_sequence.py, test/functional/feature_csv_activation.py
- Remove `LOCKTIME_VERIFY_SEQUENCE`.
- Mitigate buggy miner_tests test by setting nSequence to valid values before adding them to the mempool.
=> BIP-68 (LOCKTIME_VERIFY_SEQUENCE) from genesis

src/consensus/consensus.h, src/miner.cpp, src/policy/policy.h, src/test/miner_tests.cpp, src/validation.cpp, test/functional/feature_csv_activation.py
- Remove `LOCKTIME_MEDIAN_TIME_PAST` flag.
- Always use GetMedianTimePast() for CLTV calculations.
- Fix `test/functional/feature_csv_activation.py`, `bip113signed1` and `bip113signed2` are now invalid.
=> Mtp locktime from genesis

src/test/miner_tests.cpp, src/test/validation_block_tests.cpp, src/validation.cpp, test/functional/abc-transaction-ordering.py
- Always enforce BIP-34 block height in coinbase.
- Remove BIP-30 check, as that now is unnecessary.
- In `src/test/validation_block_tests.cpp`, put block height in coinbases.
- In `src/test/miner_tests.cpp`, put block height in coinbases and redo PoW.
=> Enforce BIP-34 coinbase height from genesis

src/validation.cpp, test/functional/feature_cltv.py, test/functional/feature_dersig.py
- Removes restrictions on nVersion of blocks.
- Fixes tests that check if certain block versions are invalid.
=> Remove block version restriction

src/init.cpp, src/test/util/setup_common.cpp, src/validation.cpp, src/validation.h, test/functional/abc-invalid-chains.py, test/functional/abc-magnetic-anomaly-mining.py, test/functional/abc-sync-chain.py, test/functional/abc-transaction-ordering.py, test/functional/abc_feature_minerfund.py, test/functional/abc_mining_basic.py, test/functional/abc_wallet_standardness.py, test/functional/example_test.py, test/functional/feature_assumevalid.py, test/functional/feature_bip68_sequence.py, test/functional/feature_csv_activation.py, test/functional/feature_dersig.py, test/functional/logos_enforce_standard_consensus.py, test/functional/mining_basic.py, test/functional/p2p_fingerprint.py, test/functional/p2p_invalid_block.py, test/functional/p2p_sendheaders.py, test/functional/p2p_unrequested_blocks.py, test/functional/wallet_resendwallettransactions.py
- Add `fRequireStandardConsensus` flag:
- Enforces IsStandardTx on txs in a block (including the coinbase).
- Adds STANDARD_SCRIPT_VERIFY_FLAGS to the script flags for txs in a block.
- Adds `-allownonstdtxnconsensus` option (defaults to `-acceptnonstdtxn`) to disable the above behavior.
- `-allownonstdtxnconsensus=1` by default for tests in `BasicTestingSetup`.
- Add `-allownonstdtxnconsensus=1` in functional tests that depend on non-standard txs in blocks, but which didn't enable `-acceptnonstdtxn`.
=> Add fRequireStandardConsensus global and -allownonstdtxnconsensus option

src/validation.cpp
- Makes sure `SCRIPT_ENABLE_SIGHASH_FORKID` is always enabled.
- This actually breaks no tests. Presumably, we fixed those in a previous commit.
=> Enforce SIGHASH_FORKID from genesis

src/consensus/tx_verify.cpp, src/test/miner_tests.cpp, src/test/transaction_tests.cpp
- Enforce transaction size limit from genesis, not only after `IsMagneticAnomalyEnabled` is true.
- In `miner_tests.cpp`, make coinbase string 100 bytes (and redo the PoW).
- In `miner_tests.cpp`, make all transactions greater than 100 bytes by adding an OP_RETURN padding output.
- Fix `txsize_activation_test`, check from genesis now and only once.
=> Enforce undersize rule from genesis

src/chainparams.cpp, src/net_processing.cpp, src/pow/test/aserti32d_tests.cpp, src/test/miner_tests.cpp, src/validation.cpp, test/functional/feature_assumevalid.py
- Set `nPowTargetSpacing` to 120 seconds.
- Reduce `STALE_CHECK_INTERVAL` to 120 seconds.
- Fix ASERT tests; as corrolary they are now variable to `t_block`.
- Redo PoW in `miner_tests.cpp`.
- Reduce `GetBlockProofEquivalentTime` required for `assumevalid` to 5 days from 14 days (otherwise `feature_assumevalid.py` takes forever)
- Bump number of blocks in `feature_assumevalid.py` to satify `GetBlockProofEquivalentTime`.
=> Change blocktime to 2 minutes

src/hash.h, src/test/hash_tests.cpp
=> [backport#19601] Add single sha256 call to CHashWriter

src/hash.cpp, src/hash.h, src/test/hash_tests.cpp
This adds the TaggedHash function as defined by BIP340 to the hash module, which
is used in BIP340 and BIP341 to produce domain-separated hashes.
Part .
Required for #88.
=> [backport#19953] Add TaggedHash function (BIP 340)

src/primitives/transaction.h, src/script/bitcoinconsensus.cpp, src/script/interpreter.cpp, src/test/CMakeLists.txt, src/test/script_p2sh_tests.cpp, src/test/sigcache_tests.cpp, src/test/sighash_bip341_tests.cpp, src/test/transaction_tests.cpp, src/test/txvalidationcache_tests.cpp, src/validation.cpp
This is required for the BIP341 sighash.
=> Add spent outputs to PrecomputedTransactionData

src/bench/rpc_blockchain.cpp
62c2bc5 added the requirement to check LowS for verbose serialization of sigs, but we didn't fix the benchmarks.
=> Fix bench-bitcoin bug in BlockToJsonVerbose benchmark.

src/test/denialofservice_tests.cpp, src/test/script_p2sh_tests.cpp, src/test/script_tests.cpp
In a few places, SignSignature is called with transactions that have inputs that don't have a corresponding output.
- In DoS_mapOrphans, adds 2777 inputs to `tx`, but doesn't add the corresponding outputs to `txPrev`.
- In AreInputsStandard, someone typed 5 instead of 4.
- In script_combineSigs, `txFrom` is updated, but `txTo` doesn't have its corresponding prevout updated.
=> Fix broken tests: SignSignature is called for tx with invalid inputs

src/primitives/transaction.h, src/script/interpreter.cpp, src/test/sighash_bip341_tests.cpp
Precompute BIP341 sighash data. Avoids quadratic hashing for the BIP341 sighash.
Required for #88.
=> Precompute bip341 data

src/bitcoin-tx.cpp, src/psbt.cpp, src/rpc/rawtransaction.cpp, src/script/sign.cpp, src/script/sign.h, src/test/descriptor_tests.cpp, src/test/fuzz/script_sign.cpp, src/test/script_tests.cpp, src/test/transaction_tests.cpp, src/test/txvalidationcache_tests.cpp
This is so we can sign BIP341 signatures, which need the spent outputs, which is provided in PrecomputedTransactionData.
=> Require PrecomputedTransactionData in MutableTransactionSignatureCreator

src/bench/verify_script.cpp, src/script/interpreter.cpp, src/script/interpreter.h, src/script/script_exec_data.h, src/test/sigcheckcount_tests.cpp, src/test/sighash_bip341_tests.cpp
This is required to collect the data for the BIP341 sighash, which, among other things, contains the last executed codeseparator position.
Required for #88.
=> Add ScriptExecutionData and thread it through EvalScript.

src/script/interpreter.cpp, src/script/interpreter.h, src/script/sign.cpp, src/test/multisig_tests.cpp, src/test/script_tests.cpp, src/test/sighash_tests.cpp, src/test/txvalidationcache_tests.cpp
It now returns bool instead of uint256, and gets the output as parameter.
This is required for BIP341, because sighash calculation can fail there.
=> Make SignatureHash fallible

src/bitcoin-tx.cpp, src/rpc/rawtransaction.cpp, src/script/interpreter.h, src/script/sign.cpp, src/script/sign.h, src/test/multisig_tests.cpp, src/test/script_p2sh_tests.cpp, src/test/script_tests.cpp, src/test/transaction_tests.cpp, src/wallet/wallet.cpp
Basically deletes the constructor which sets txdata to nullptr.
This change is required for BIP341 sighashes, as PrecomputedTransactionData contains m_spent_outputs, which is required for computing parts of the sighash.
=> Always require PrecomputedTransactionData in GenericTransactionSignatureChecker

src/bench/verify_script.cpp, src/script/interpreter.cpp, src/script/interpreter.h, src/script/script_exec_data.h, src/script/sign.cpp, src/script/sign.h, src/test/fuzz/script_sign.cpp, src/test/multisig_tests.cpp, src/test/script_tests.cpp, src/test/sigcheckcount_tests.cpp, src/test/sighash_bip341_tests.cpp, src/test/sighash_tests.cpp, src/test/txvalidationcache_tests.cpp
ScriptExecutionData contains `codeseparator_pos` and `executed_script_hash`, which is required for the BIP341 sighash.
=> Refactor: thread ScriptExecutionData to SignatureHash.

src/script/interpreter.cpp, src/script/script.cpp, src/script/script.h, src/script/script_error.cpp, src/script/script_error.h, src/test/data/script_tests.json, src/test/script_tests.cpp, test/functional/test_framework/script.py
This marker opcode allows us to introduce new models of execution, such as Taproot.
=> Rename OP_VER to OP_SCRIPTTYPE, add INVALID_OP_SCRIPTTYPE.

src/pubkey.cpp, src/pubkey.h, src/test/CMakeLists.txt, src/test/taproot_tests.cpp
This the base point tweaked by a tweak; in other words this + tweak*G.
This is required for Taproot, for verifying that the hash of the tapleaf combined with the base point results in the commitment.
=> Add CPubKey::AddScalar

src/CMakeLists.txt, src/script/taproot.cpp, src/script/taproot.h, src/test/taproot_tests.cpp
This verifies a given script is part of the given Taproot commitment. It's required for implementing Taproot as output type.
Note: VerifyTaprootCommitment requires certain length invariants to be upheld, this has to be ensured by the caller.
=> Add VerifyTaprootCommitment

src/script/taproot.cpp, src/script/taproot.h, src/test/taproot_tests.cpp
This returns whether a script is a valid Taproot output script.
Valid scripts can be either of these:
- `OP_SCRIPTTYPE OP_1 <33-byte commitment>
- `OP_SCRIPTTYPE OP_1 <33-byte commitment> <32-byte state>
=> Add IsPayToTaproot

src/script/script_error.cpp, src/script/script_error.h, src/script/script_flags.h, src/script/sigencoding.cpp, src/test/checkdatasig_tests.cpp, src/test/schnorr_tests.cpp, src/test/script_tests.cpp, src/test/sigencoding_tests.cpp, src/test/txvalidationcache_tests.cpp
Ensures that signatures are Schnorr signatures (64 byte long + sig hash flag) and use the BIP341 sighash.
This flag is required for verifying signatures for the Taproot key spend path (spending without revealing the script).
It is never set during script execution, only during signature verification.
=> Add SCRIPT_TAPROOT_KEY_SPEND_PATH script flag

src/script/interpreter.cpp, src/script/script_error.cpp, src/script/script_error.h, src/script/script_exec_data.h, src/test/script_tests.cpp, src/test/taproot_tests.cpp, test/functional/logos_feature_taproot_script_path.py, test/functional/test_framework/key.py
This allows spending an output by revealing the interal pubkey, a leaf script and a merkle path proving the commitment.
=> Add script spend path for Taproot

src/chainparams.cpp
- New coinbase string
- Genesis output script is OP_RETURN; is unspendable anyway
- Set genesis time to 13th April 2021, 00:00:00 UTC
=> Update testnet genesis block

src/chainparams.cpp
Testnet coins are worthless anyway; this will allow mining pools to test their setup.
It'll also allow us to test new coinbase outputs on the testnet.
=> Enforce Logos coinbase rule on testnet

src/policy/policy.cpp, src/test/transaction_tests.cpp
Currently, non-pushonly scriptSigs are non-standard; but mining pool software relies on the scriptSig of the coinbase being arbitray.
We enforce standardness on all txs, so blocks having non-pushonly coinbases scriptSigs will be rejected, which is not what we want.
This will remove the "scriptsig-not-pushonly" restriction for standardness on coinbase inputs.
=> Make non-pushonly scriptsig in coinbase inputs standard

src/rpc/mining.cpp
Otherwise, getblocktemplate fails with "scriptpubkey", as the dummy output created is non-standard.
=> Fix: Make getblocktemplate create a standard scriptDummy

src/qt/guiconstants.h
This fixes a bug where the Qt wallet would use the old Bitcoin ABC datadir, causing all sorts of problems
=> Update QAPP_* constants

src/chainparams.cpp
This makes it so that the progress in the log is displayed (somewhat) correctly
Closes #148.
=> Update testnet chainTxData

src/bench/duplicate_inputs.cpp, src/miner.cpp, src/rpc/blockchain.cpp, src/test/validation_tests.cpp, src/validation.cpp, src/validation.h
This will allow us to build a coin where the block reward depends on difficulty.
=> Refactor GetBlockSubsidy to depend on nBits instead of nHeight

src/miner.cpp, src/miner.h, src/rpc/mining.cpp
This fixes a bug where when the testnet resets the nBits to 0x1c100000, the coinbase outputs would remain unchanged, resulting in invalid blocks.
=> Fix getblocktemplate for testnet

src/CMakeLists.txt, src/addresses/xaddress.cpp, src/addresses/xaddress.h, src/test/CMakeLists.txt, src/test/xaddress_tests.cpp
This is the first commit required to implement parsing XAddress
formats. The basic idea is that addresses are composed of 4 parts:
1. token prefix (all lowercase word characters)
2. network byte (capital word character)
3. base58 encoded payload
4. base58 encoded 4-byte weak sha256d hash of (1)|| (2) || (3)
A follow up commit will implement processing into a `CTxDestination`
to support use in the rest of the node.
=> Implement raw encoding and decoding on XAddress format

src/addresses/xaddress.cpp, src/addresses/xaddress.h, src/test/xaddress_tests.cpp
Adds a `Parse` method to the XAddress namespace that uses the
XAddress Decode operation and then feeds it into `ExtractDestination`.
This returns a CTxDestination which is usable in the rest of the code
base and wallet.
=> Implement XAddress parsing

src/addresses/xaddress.cpp, src/addresses/xaddress.h, src/test/xaddress_tests.cpp
Wraps XAddress::Encode in a helper function to directly create a
XAddress for Lotus from a CTxDestination. This type is used in
the wallet and rpc several places, and so support for this is
needed to connect XAddresses into the rest of the codebase.
=> Implement encoding CTxDestinations to XAddresses

src/qt/bitcoinamountfield.cpp, src/qt/bitcoinunits.cpp, src/qt/bitcoinunits.h, src/qt/coincontroldialog.cpp, src/qt/guiutil.cpp, src/qt/optionsmodel.cpp, src/qt/overviewpage.cpp, src/qt/test/uritests.cpp, src/qt/test/wallettests.cpp
The QT Wallet uses completely different formatters from the rest of
the codebase and was missed during the previous re-denomination patch.
This commit changes the QT wallet to use the 10^6 base unit, and ensures
the QT wallet uses the appropriate formats.
=> Update unit formating in QT to be 10^8 and Lotus properly

src/config.cpp, src/config.h, src/init.cpp, src/miner.cpp, src/miner.h, src/minerfund.cpp, src/minerfund.h, src/rpc/mining.cpp, src/test/blockfilter_index_tests.cpp, src/test/miner_tests.cpp, src/validation.cpp, src/validation.h
This commit adds `enableMinerFund` to the config so that it can be
overriden in w/o setting gArgs. It also adds flags to the
`BlockAssembler` options as well as the validation options in order to
support passing these configs down to the appropriate code. However,
current testing setup relies on the global `GetConfig()` singleton. This
singleton always returns the chainparams from the global `Params()`
singleton function. The testing setup changes the Params after
initialization, thus we need to ensure that `EnableMinerFund()` returns
the appropriate default consensus parameter if it has not been formally
set by the command line or the testing setup. In the future, global
singletons should be removed so that tests can be ran in parallel.
However, this requires substantial refactors to the …
=> Add `enableMinerFund` to config to enable testing

src/config.h, src/test/config_tests.cpp, src/test/miner_tests.cpp
Currently, minerfund is only allowed to be enabled on regtest. This
commit allows it do be disabled on mainnet and testnet, as well as in
unit tests.
=> Allow minerfunding to be disabled on mainet/testnet

src/rpc/mining.cpp, test/functional/logos_rpc_getrawunsolvedblock.py
This API takes an address and returns a target, and the serialized block
as hex. Because the nonce was expanded, there is no need to grind on the
coinbase in order to produce a valid block. Thus, we can implement a
miner which takes only the block header. However, currently we also
include the transactions as there is no internal caching for the
transaction set. These are needed in submit block for validating the
merkle root and broadcasting the transactions later. Mining software
will need to hold on to them, but does not need to do anything with
them.
=> Implement a new simplified mining API `getunsolvedblock`

src/policy/policy.cpp, src/policy/policy.h, src/test/transaction_tests.cpp, test/functional/mempool_accept.py
Now the limit is the general 10000 byte script limit.
Through larger opcode limits and the addition of Taproot, smart contracts might require more bytes as inputs.
There is no DoS vector, since each byte has to be paid for, and there are cheaper ways to generate lots of bytes (e.g. OP_NUM2BIN/OP_3DUP). Quadratic hashing is also not of concern anymore.
=> Remove 1650 byte scriptSig limit

test/functional/rpc_generateblock.py
While redenominating the code to 10^6 from 10^8, this particular
spot was missed. The test continued to pass because `listunspent` is
nondeterministic. Sometimes it was pulling a tx with sufficient funds,
and sometimes it was creating transactions that overspent. This change
ensures that both transactions that can be used in subsequent lines
have enough funds to pass the test.
=> Ensure rpc_generateblock always passes

src/chainparams.cpp
As per title. These seeders won't register or provide Lotus nodes to
us. We will need to setup our own seeders and add them here later.
=> Remove BCHA seeders in prep for testnet and mainnet launches

src/chainparams.cpp, src/consensus/addresses_mainnet.h, src/consensus/addresses_regtest.h, src/consensus/addresses_testnet.h, src/consensus/params.h, src/minerfund.cpp, src/minerfund.h, src/test/CMakeLists.txt, src/test/miner_tests.cpp, src/test/minerfund_tests.cpp, test/functional/abc_mining_basic.py, test/functional/logos_feature_minerfund.py
We've decided to implement a lottocracy for the system of governance on
Lotus. As such, each weak (epoch) a set of random citizens will be
selected to receive a portion of the block reward which they may
allocate however they want. This code implements the random selection
from a list of addresses of verified citizens. This is subject to modulo
bias, however the effect is miner given the use case. In the future,
better algorithms may be implemented.
=> Implement random selection of output addresses based on epoch block

src/chainparams.cpp
Update Genesis block to have a time of the summer solstice in 2021, and
a block hash starting with `abc`.
=> Update genesis blocktime and nonce for mainnet

src/chainparams.cpp, src/consensus/params.h, src/validation.cpp
Updating activation time to winter solstice 2021:
2021-12-21T15:59:00.000Z
Obtained timing from: https://www.weather.gov/media/ind/seasons.pdf
=> Update Exodus upgrade activation time

test/functional/abc_rpc_ecash.py
Was missed due to other test failures during the merge ov v0.23.6.
This adjust the expectation to pass properly.
=> Fix ticker symbol check in `abc_rpc_ecash.py`

src/chainparams.cpp, src/seeder/bitcoin.cpp, src/seeder/db.h
Hi @schancel,
I try to implement the fix for the seeder but I got some issues:
* When running the seeder on a vps, it can only crawl the directly connected node, not the other nodes.
* Even though the nslookup returns the node's addresses (I can see it while debugging), but no data is sync for lotusd (with config: dnsseed=1, connect=1)
My DNS config for the domain abcpay.cash is:
| Type | Host | Value |
|----------|----------|---|
| A Record | seeder | 167.179.88.165 |
| NS Record | dnsseed | seeder.abcpay.cash |
The command I ran the dnsseed is:
```
sudo ./lotus-seeder -ns=seeder.abcpay.cash -mbox=test@gmail.com -chain=test -host=dnsseed.abcpay.cash -port=53
```
Could you help to check?
Thanks!
=> Fix lotus seeder checkpoints height

src/qt/bitcoinaddressvalidator.cpp, src/qt/test/bitcoinaddressvalidatortests.cpp
We overlooked that on mainnet underscore characters are part of the
address. The validation of the address fields in QT don't currently
allow underscores. This commit adds them to the list of valid characters
so that we can use the QT interfaces to send and receive mainnet Lotus.
=> Allow mainnet XAddresses to be input into QT address fields

CMakeLists.txt, contrib/aur/lotus-qt/PKGBUILD, contrib/aur/lotus/PKGBUILD
* Fixes a problem with the seeder segfaulting when there are no
checkpoints.
* Fixes the input dialog validation to allow lotus mainnet addresses.
=> Bump version to 1.0.1

src/addresses/xaddress.cpp, src/qt/test/guiutiltests.cpp, src/qt/test/uritests.cpp, src/test/dstencode_tests.cpp, src/test/xaddress_tests.cpp, test/util/data/bitcoin-util-test.json, test/util/data/tt-delin1-out.json, test/util/data/tt-delout1-out.json, test/util/data/tt-locktime317000-out.json, test/util/data/txcreate1.json, test/util/data/txcreatedata1.json, test/util/data/txcreatedata2.json, test/util/data/txcreatedata_seq0.json, test/util/data/txcreatedata_seq1.json, test/util/data/txcreatemultisig1.json, test/util/data/txcreatemultisig2.json, test/util/data/txcreatescript2.json, test/util/data/txcreatesignlotusv1-all.json, test/util/data/txcreatesignlotusv2-all-anyonecanpay.json, test/util/data/txcreatesignlotusv2-all.json, test/util/data/txcreatesignlotusv2-none-anyonecanpay.json, test/util/data/txcreatesignlotusv2-none.json, test/util/data/txcreatesignlotusv2-single-anyonecanpay.json, test/util/data/txcreatesignlotusv2-single.json, test/util/data/txcreatesignv1.json
Due to using CHashWriter, we were including VarInt sizes for the
two vectors which were included. This was a mistake and not within
the specification. This commit adds some extra checks, changes the
hash generation function, and introduces a second check to enable
legacy addresses to pass decoding for the time being.
=> Fix commitment in XAddress check byte hash calculation

CMakeLists.txt, contrib/aur/lotus-qt/PKGBUILD, contrib/aur/lotus/PKGBUILD
* Fixes an issue with check byte generation in XAddresses, but leases
backwards compatible support for existing addresses in the wild. This
will be removed in version 2.0.0.
* Merges in latest changes from Bitcoin ABC v0.26.7
=> Bump version to 1.0.2

src/addresses/xaddress.cpp
The constructor used in part of the implementation for XAddresses is
using a `std::vector` constructor that is not supported until C++20. This
commit instead uses `std::copy` to perform the same operation.
=> Make XAddress parser C+11 compliant

test/functional/abc_rpc_avalancheproof.py
This little guy got errorenously merged when backporting v0.23.6.
Delete it.
=> Remove spurious print in `abc_rpc_avalancheproof`

src/chainparams.cpp, src/consensus/addresses_mainnet.h, src/consensus/addresses_regtest.h, src/consensus/addresses_testnet.h, src/consensus/params.h, src/key_io.cpp, src/minerfund.cpp, src/minerfund.h, src/test/minerfund_tests.cpp
Previously, the coinbase outputs for the minerfund were randomly picked from a set of addresses based on `hashEpochBlock`.
However, establishing such a set turned out to be difficult. Therefore, the address sets always contained only one entry, so that address would always be picked.
This PR removes picking the addresses at random, in order to simplify adding activation code down the line.
=> Refactor minerfund, remove random selection

src/chainparams.cpp, src/consensus/params.h, src/init.cpp, src/validation.cpp
Nodes automatically fork off from the network if not upgraded at the determined timestamp.
This change bumps the "fork off" timestamp (replayprotectiontime) to 2022-06-21 09:14:00, such that the node continues to accept normally signed (non-replay protected) transactions at the Exodus network upgrade.
=> Add `leviticusactivationtime`, bump replay protecc

CMakeLists.txt, contrib/aur/lotus/PKGBUILD
This version supports the December Solstice network upgrade (Exodus).
=> Bump version to 2.0.3

contrib/teamcity/download-apple-sdk.sh
Previous, this URL was removed from being public by Bitcoin ABC due to
the original resource hosting this being taken down. However, Bitcoin
Core also hosts the SDK. This commit changes the default parameter for
where to download the SDK to use Core's repository.
=> Fix default param in `download-apple-sdk.sh`

cmake/platforms/Linux32.cmake, cmake/platforms/Linux64.cmake, cmake/platforms/LinuxAArch64.cmake, cmake/platforms/LinuxARM.cmake, cmake/platforms/OSX.cmake, cmake/platforms/Win32.cmake, cmake/platforms/Win64.cmake, contrib/gitian-descriptors/gitian-linux.yml, contrib/gitian-descriptors/gitian-osx.yml, contrib/gitian-descriptors/gitian-win.yml
Currently, the platform toolchain cmake files (Linux32.cmake, OSX.cmake, etc.) all use CMAKE_CURRENT_SOURCE_DIR to build the toolchain path.
This breaks however once the toolchain files are used from a different source directory, e.g. when building dependencies.
By threading the BASEPREFIX through the build system, the toolchain files can also be used by dependencies.
=> Use BASEPREFIX in platform toolchain cmake files

depends/Makefile, depends/packages/Flatbuffers.mk, depends/packages/native_Flatbuffers.mk, depends/packages/packages.mk
This is used by the nng interface down the line.
The native_Flatbuffers.mk is for building flatc, which has to be built with the host architecture. Flatbuffers.mk builds for the target architecture, which is then used by lotusd.
=> Add Flatbuffers dependency

depends/Makefile, depends/packages/nng.mk, depends/packages/packages.mk, depends/patches/nng/remove_deps.patch
This is used by the nng interface down the line.
`nngcat` causes problems when cross-compiling, and isn't used anyway, so we disable it.
=> Add nng dependency

src/interfaces/chain.cpp, src/validation.cpp, src/validationinterface.cpp, src/validationinterface.h, src/zmq/zmqnotificationinterface.cpp, src/zmq/zmqnotificationinterface.h
Access to `spent_coins` is required for the NNG interface. This adds it to `CValidationInterface`.
=> Add `spent_coins` to TransactionAddedToMempool

contrib/utils/install-dependencies.sh
The new nanomsg interface for writing plugins requires flatbuffers and
nng as part of the build process. This change includes these in the
docker image intended for running development builds on CI.
=> Update development image to include flatbuffers and nng

src/consensus/activation.cpp, src/consensus/activation.h, src/test/activation_tests.cpp
Returns whether MTP has moved past `leviticusactivationtime`.
=> Add `IsLeviticusEnabled`

CMakeLists.txt, contrib/aur/lotus/PKGBUILD
Supports the Leviticus network upgrade.
=> Bump version to 3.1.3

src/consensus/addresses_testnet.h
When removing the random selection of addresses, there was a copy
and paste error which changed the miner fund addresses for the genesis
testnet fork. This commit changes those addresses back so that the
testnet blocks validate from a brand new resync.
=> Fix testnet minerfund addresses

src/nng_interface/nng_interface.cpp
This would calculate the wrong undo pos for blocks that have exactly 253 transactions.
=> Fix off-by-one bug in `GetFirstUndoOffset`

src/chainparams.cpp
Currently, the PoW limit for the testnet is needlessly high with a minimum difficulty of ~16. This change reduces the difficulty to 1.
=> Set min testnet difficulty to 1

src/test/validation_tests.cpp, src/validation.cpp
Currently, this function asserts nBits <= 0x1c100000, but the on the testnet, this can now fall below that, so we simply cap the subsidy in this case.
=> Fix `GetBlockSubsidy` for difficulty < ~16

CMakeLists.txt, contrib/aur/lotus/PKGBUILD
* Fixes address bug which caused the testnet to become corrupted
(Did not effect mainnet)
* Drop testnet difficulty to 1
* Use same address sets for testnet, mainnet, and regtest to avoid
future confusion.
* Fix off by one error in nng interface for chronik and other services
=> Bump version number to 3.3.3

test/functional/test_framework/ripemd160.py, test/functional/test_framework/script.py
OpenSSL 3 removed `ripemd160`, see https://github.com/openssl/openssl/issues/16994
Thus, the functional tests fail on systems with OpenSSL 3.
This is a backport of https://reviews.bitcoinabc.org/D11413
=> Fix functional tests with OpenSSL 3

doc/build-unix.md, doc/dependencies.md
Add in missing documentation about flatbuffers and nng dependencies to
the build documentation.
=> [docs] Add dependencies and build instructions for NNG and flatbuffers

src/fs.cpp, src/wallet/test/db_tests.cpp, src/wallet/test/init_test_fixture.cpp
This is a backport of https://reviews.bitcoinabc.org/D10769
It is needed to run `ninja check` with boost 1.77.
The error I'm getting without this is:
```
/home/p/dev/lotusd/src/wallet/test/init_test_fixture.cpp: In constructor ‘InitWalletDirTestingSetup::InitWalletDirTestingSetup(const string&)’:
/home/p/dev/lotusd/src/wallet/test/init_test_fixture.cpp:37:52: error: ‘std::map<std::__cxx11::basic_string<char>, boost::filesystem::path>::mapped_type’ {aka ‘class boost::filesystem::path’} has no member named ‘BOOST_FILESYSTEM_C_STR’
37 |     std::ofstream f(m_walletdir_path_cases["file"].BOOST_FILESYSTEM_C_STR);
|                                                    ^~~~~~~~~~~~~~~~~~~~~~
```
=> Fix build with Boost 1.77.0

test/functional/interface_nng.py
[test] fix Python 3.10 asyncio DeprecationWarning
With Python 3.10, calling `asyncio.get_event_loop().run_until_complete`  raises a `DeprecationWarning`, which is interpreted as a failure by the test framework because there should be nothing on stderr.
```
Running Unit Tests for Test Framework Modules
..........
----------------------------------------------------------------------
Ran 10 tests in 0.059s
OK
interface_nng.py started
interface_nng.py failed, Duration: 2 s
stdout:
2022-11-01T07:38:25.753000Z TestFramework (INFO): Initializing test directory /home/pierre/dev/lotusd/build/test/tmp/test_runner_₿₵_🏃_20221101_083825/interface_nng_0
2022-11-01T07:38:27.486000Z TestFramework (INFO): Stopping nodes
2022-11-01T07:38:27.487000Z TestFramework (INFO): Cleaning up …
```
=> fix Python 3.10 asyncio DeprecationWarning

src/chainparams.cpp
Due to dyslexia, the replace activation time was set to `2022-12-12T21:48:00.000Z` instead of `2022-12-21T21:48:00.000Z`. This will impact miners and users insomuch as they will mine empty blocks -- but only if they do not upgrade. As everyone will need to upgrade in order to get the new functionality for the numbers upgrade, this will be fine.
=> Fix numbers activation time to be winter solstice

src/networks/abc/checkpoints.cpp
Add in the exodus checkpoint for recordkeeping, and also fix the leviticus checkpoint as it was one block after the upgrade. The miner fund addresses change one block after each upgrade.
=> Add exodus checkpoint + fix leviticus checkpoint

src/chainparams.cpp, src/consensus/activation.cpp, src/consensus/activation.h, src/consensus/params.h, src/init.cpp, src/test/CMakeLists.txt, src/test/activation_tests.cpp, src/validation.cpp, test/functional/logos_feature_minerfund_activation.py
Nodes automatically fork off from the network if not upgraded at the
determined timestamp. This change bumps the "fork off" timestamp
(replayprotectiontime) to 2023-06-21T14:58:00.000Z (Deuteronomy
upgrade), such that the node continues to accept normally signed
(non-replay protected) transactions at the "Numbers" network upgrade.
=> Add numbersactivationtime and, bump replay protecc time

src/validation.cpp, test/functional/logos_enforce_standard_consensus.py, test/functional/logos_fix_acceptnonstdtxn_scripts.py
Specifying `-acceptnonstdtxn=1` currently still rejects spending non-standard Scripts containing e.g. OP_NOP10. This change fixes this.
=> Fix `-acceptnonstdtxn=1` to also work for non-standard Scripts

contrib/source-control-tools/patch-recipes/update-chainparams.sh
Script now looks for an env var called `CONFIG_FILE` that will override the default config location. Can be ran as:
```
CONFIG_FILE=CONFIG_FILE=~/Library/Application\ Support/Lotus/lotus.conf contrib/source-control-tools/patch-recipes/update-chainparams.sh
```
=> Fix `update-chainparams.sh` so it can be ran on MacOS X
