src/chainparams.cpp, test/functional/feature_loadblock.py
=> New disk magic for main, test and regtest

src/script/interpreter.cpp, src/test/data/script_tests.json
- Disables the remaining reserved opcodes
=> Disable reserved opcodes

src/networks/abc/checkpoints.cpp, src/test/checkpoints_tests.cpp
=> Remove checkpoints

src/chainparams.cpp, src/chainparams.h, src/init.cpp, src/validation.cpp
=> Default to -acceptnonstdtxn=0 on testnet

src/policy/policy.cpp, src/test/transaction_tests.cpp, test/functional/mempool_accept.py
=> Raise max number of OP_RETURN outputs to 3

src/hash.cpp, src/hash.h, src/test/hash_tests.cpp
=> [backport#19601] Add SHA256Uint256 helper functions

src/script/interpreter.cpp
This is to make it easy to add SignatureHashBIP341 later on.
=> Refactor SignatureHash, split into SignatureHashLegacy and SignatureHashBIP143

src/util/system.cpp
Respectively updates Windows and Mac default datadirs
=> Change default datadir from ~/.bitcoin to ~/.lotus

src/CMakeLists.txt, src/test/CMakeLists.txt, src/test/intmath_tests.cpp, src/util/intmath.cpp, src/util/intmath.h
This allows computing the log2 using deterministic integer arithmetic.
Required for making block reward equal to log(difficulty).
=> Add Log2FixedPoint

src/clientversion.cpp, src/test/net_tests.cpp, test/functional/abc-cmdline.py, test/functional/abc_rpc_excessiveblock.py
=> Update network client name to lotusd from Bitcoin ABC

CMakeLists.txt, contrib/aur/bitcoin-abc-qt/PKGBUILD, contrib/aur/bitcoin-abc/PKGBUILD, contrib/debian/copyright, contrib/debian/watch, contrib/gitian-build.py, contrib/gitian-descriptors/gitian-linux.yml, contrib/gitian-descriptors/gitian-osx.yml, contrib/gitian-descriptors/gitian-win.yml, contrib/release/github-release.sh, doc/build-osx.md, doc/build-unix.md, doc/build-windows.md, doc/files.md, doc/gitian-building.md, doc/gitian-building/gitian-building-mac-os-sdk.md, doc/gitian-building/gitian-building-manual.md, doc/gitian-building/gitian-building-setup-gitian-debian.md, doc/gitian-building/gitian-building-setup-gitian-fedora.md, doc/release-notes/release-notes-0.21.8.md, doc/release-process.md, src/init.cpp
=> Update github repo urls for gitian and building

src/chainparams.cpp, src/consensus/params.h, src/test/miner_tests.cpp, src/test/validation_tests.cpp, src/validation.cpp
This dampens price volatility slightly
=> Change GetBlockSubsidy to emit coins based on log(difficulty)

src/test/miner_tests.cpp
This commit stops CreateNewBlock_validity from checking miner funding
in the coinbase, as well as makes finding txIds in the blocks more
generic. The second change makes updating the test less fragile. The
specific ordering is no longer important since the introduction of
CTOR.
=> Remove checking of miner funding from CreateNewBlock_validity test

src/chainparams.cpp
=> Update genesis block for testnet

src/consensus/addresses_mainnet.h
* Updating Bitcoin-ABC's address.
* Update one address to be managed differently.
=> Finalize reward addresses for first mainnet release

src/consensus/activation.cpp, src/consensus/activation.h, src/init.cpp, src/test/CMakeLists.txt, src/test/activation_tests.cpp, test/CMakeLists.txt, test/functional/test_framework/test_framework.py, test/lint/check-doc.py
Checks whether the Exodus upgrade has activated yet, based on MTP.
=> Add `IsExodusEnabled`

src/consensus/addresses_mainnet.h, src/consensus/addresses_regtest.h, src/consensus/addresses_testnet.h, src/consensus/params.h, src/minerfund.cpp, src/test/minerfund_tests.cpp, test/functional/logos_feature_minerfund.py, test/functional/logos_feature_minerfund_activation.py
Coinbase addresses are going to update during the Exodus hardfork to new recipients.
=> Update coinbase addresses for Exodus hardfork

CMakeLists.txt, contrib/aur/lotus/PKGBUILD
This version supports the NNG interface for allowing easy indexing.
=> Bump version to 2.1.3

CMakeLists.txt, contrib/aur/lotus/PKGBUILD
Replay protection timing was not bumped in previous release.
=> Bump version to 3.2.3 for new release

src/networks/abc/checkpoints.cpp
=> Add checkpoint for leviticus hardfork on mainnet

src/chainparams.cpp
This allows to simulate activation before and make sure everything works properly.
=> Activate testnet 21 days before mainnet

src/consensus/addresses.h
ABC changed their lang config. Update this file.
=> Fix linting of src/consensus/addresses.h

src/chainparams.cpp, src/consensus/activation.cpp, src/consensus/activation.h, src/consensus/addresses.h, src/consensus/params.h, src/init.cpp, src/minerfund.cpp, src/validation.cpp, test/functional/logos_feature_minerfund_activation.py
Make all necessary preparations for the Joshua upgrade Dec 22, 2023.
Used 6e2e115 as a template for this commit.
Still need to finish the Python test and actually bump the version numbers. Will add the version bump in the next commit.
=> Joshua protocol upgrade

src/consensus/addresses.h, test/functional/logos_feature_minerfund_activation.py
Updates the consensus and the Python functional test accordingly.
=> Use new reward address

CMakeLists.txt, contrib/aur/lotus-qt/PKGBUILD, contrib/aur/lotus/PKGBUILD
=> Bump version to 6.3.3 for Joshua upgrade

src/networks/abc/checkpoints.cpp
Added the checkpoint block height/hash to the `checkpoints.cpp` file, not sure if anything else needs to be done
=> Add Joshua checkpoint block height/hash
